server:
  #端口
  port: 9898
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://172.16.100.117:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
      cache: false
code:
  verify: false



