server:
  #端口
  port: 9898
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/dining-hall?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ZnA*r0JuuV7B
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: ioui*we&wen
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
code:
  verify: true
file:
  upload: http://122.51.70.250:9898
