server:
  #端口
  port: 9898
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/dining-hall?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #设置换成false
  redis:
    host: 192.168.30.170
    port: 6379
    password:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
code:
  verify: false
file:
  upload: http://localhost:9898




