#公共配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: master
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  #视图配置
  mvc:
    static-path-pattern: /static/**
  jackson:
   date-format: yyyy-MM-dd HH:mm:ss
   time-zone: GMT+8

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

