server:
  #端口
  port: 9898
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/back-ms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
      cache: false
code:
  verify: false



