#公共配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: master
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  #视图配置
  mvc:
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
  redis:
    host: localhost
    port: 6379
    password:

  servlet:
    multipart:
      maxFileSize: "1000MB"
      maxRequestSize: "10000MB"
code:
  verify: true



# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

