#公共配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #模板引擎配置
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: true
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  #缓存配置
  cache:
    type: redis
    cache-names: adms
#mybatisPlus
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.eports.ad.ms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.eports.ms.entity

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #    metaObjectHandler: com.eports.ms.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

#后台服务一级域名
domain : .e-ports-ms.com



##公共配置
#server:
#  port: 80
#  tomcat:
#    uri-encoding: UTF-8
#spring:
#  #激活哪一个环境的配置文件
#  profiles:
#    active: dev
#  main:
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#  #视图配置
#  mvc:
#    static-path-pattern: /static/**
#  #网络请求配置
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#      enabled: true
#  #模板引擎配置
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false
#    settings:
#      template_update_delay: 0
#      classic_compatible: true
#      number_format: 0.######
#      template_exception_handler: ignore
#    request-context-attribute: rc
#    charset: UTF-8
#  #连接池配置
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      validationQuery: SELECT 1
#      initialSize: 10
#      minIdle: 10
#      maxActive: 200
#      minEvictableIdleTimeMillis: 180000
#      testOnBorrow: true
#      testWhileIdle: true
#      removeAbandoned: true
#      removeAbandonedTimeout: 1800
#      logAbandoned: true
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 100
#
#  #缓存配置
#  cache:
#    type: redis
#    cache-names: adms
##mybatisPlus
#mybatis:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: com.eports.ad.ms.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号隔离
#  typeAliasesPackage: com.eports.ms.entity
#
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 3
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #    logic-delete-value: 1
#    #    logic-not-delete-value: 0
#    #自定义填充策略接口实现
#    #    metaObjectHandler: com.eports.ms.config.SysMetaObjectHandler
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    cache-enabled: false
#
##后台服务一级域名
#domain : .e-ports-ms.com
#---
##开发环境配置
#server:
#  #端口
#  port: 8080
#spring:
#  profiles: dev
#  rabbitmq:
#    host: 39.104.124.39
#    port: 5672
#    username: guest
#    password: guest
#    #    host: 192.168.30.103
#    #    port: 5672
#    #    username: epuser
#    #    password: 123456
#    virtual-host: /
#    publisher-confirms: true #开启发送确认
#    publisher-returns: true #开启发送失败退回
#    listener:
#      simple:
#        acknowledge-mode: manual #ack manual
#  #redis配置
#  redis:
#    database: 1
#    host: 192.168.30.170
#    port: 6379
#    password:      # 密码（默认为空）
#    timeout: 3000  # 连接超时时长（毫秒）
#    lettuce:
#          pool:
#            max-active: 200 #连接池最大连接数（使用负值表示没有限制）
#            max-idle: 20 # 连接池中的最大空闲连接
#            min-idle: 5 #连接池中的最小空闲连接
#            max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  # 数据源配置
#  datasource:
#    url: jdbc:mysql://192.168.30.170:3306/eports_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#  global-config:
#    logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#    logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
##日志
#logging:
#  config: classpath:log/logback.xml
#  path: D:\log\adms
#
##自定义配置属性
##源码生成文件夹
#source-code-dic:  D://adms
#source-code-zipfile:  D://源码.rar
#
##搜索文件生成包的位置
##本地路径
#lucence-dic: D://lucence
#
### pdf export config
#pdfExport:
#  fontPdf: static/layui/font/msyh.ttc
#  pdfFtl: templates/letter/pdfTemplate.ftl
#
##kindeditor编辑器
#kindeditor:
#  upload-file-max-size: 5120000
#  upload-file-server-url: http://172.16.100.104:10236/filestorage/uploadFilesAndSave